version: '3.8'

services:
  db:
    container_name: postgresDB
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5444:5432"
